spring:
  application:
    name: "configserver"
  profiles:
#    active: native     #used in classpath and file system
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"     # for classpath
#          search-locations: "file:////Users//swapnalikokare//Ranjit//Placement//Spring_Boot//eazybytes//config"
        git:
          uri: "https://github.com/ranjitkokare/eazybanks-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
# tells actuator to enable the health related information
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # groups metrics by application name
    tags:
      application: ${spring.application.name}


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"


server:
  port: 8071

# OpenTelemetry logging configuration
logging:
  pattern:
    # 5 length character before application name(log severity(warn, info, debug, error, trace))[Metadata Tag, Trace ID, Span ID]
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"