services:
  accounts:
    image: ranjitkokare/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
#   we use networks to connect multiple containers together so that they can communicate with each other
    networks:
      - eazybank
  loans:
    image: ranjitkokare/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  cards:
    image: ranjitkokare/cards:s4
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
# root element say to docker server create a network with name eazybank and use bridge driver
networks:
  eazybank:
    driver: "bridge"