server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      # using pipe we compose multiple functions as a single logical unit
      definition: email|sms
    stream:
      bindings:
        # input binding name between function and message broker
        emailsms-in-0:
          destination: send-communication # destination name is queue name
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent # exchange name
  # RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


