server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: "always"
  config:
    import: "optional:configserver:http://localhost:8071"

# Enable management related API's by activating actuator API path
management:
  endpoints:
    web:
      exposure:
        include: "*"  # all management endpoints instead of only refresh