server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      # using pipe we compose multiple functions as a single logical unit
      definition: email|sms
    stream:
      bindings:
        # input binding name between function and message broker
        emailsms-in-0:
          destination: send-communication # destination name is queue name
          group: ${spring.application.name}
        emailsms-out-0:
          destination: communication-sent # exchange name
  # Removed RabbitMQ configuration
      # Kafka configuration
      kafka:
        binder:
          brokers: # list of elements
            - localhost:9092 # endpoint URL of Kafka broker





