server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"


# Enable management related API's by activating actuator API path
management:
  endpoints:
    web:
      exposure:
        include: "*"  # all management endpoints instead of only refresh
  #  Allows us to shut down the account microservice gracefully
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true


# Eureka client configuration
eureka:
  instance:
    # By default, account microservice will try to register itself with hostname(DNS mapping)
    # But here inside our local system we don't have DNS mapping, so we register it with IP address
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


# Application information display on Eureka dashboard
info:
  app:
    name: "loans"
    description: "Eazy Bank Loans application"
    version: "1.0.0"