server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"


# Enable management related API's by activating actuator API path
management:
  endpoints:
    web:
      exposure:
        include: "*"  # all management endpoints instead of only refresh
  # tells actuator to enable the health related information
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  #  Allows us to shut down the account microservice gracefully
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true


# Eureka client configuration
eureka:
  instance:
    # By default, account microservice will try to register itself with hostname(DNS mapping)
    # But here inside our local system we don't have DNS mapping, so we register it with IP address
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


# Application information display on Eureka dashboard
info:
  app:
    name: "cards"
    description: "Eazy Bank Cards application"
    version: "1.0.0"


# Logging configuration
logging:
  level:
    com:
      eazybytes:
        cards: DEBUG